/*                       SIMA - PROFESORES
		     DETALLES DEL CONTROL DE VERSIONES

**************************************************************************
* NOMBRE DEL PROGRAMA......: VER-PROF.PRG                                *
* TITULO DEL PROGRAMA......: DETALLES DE CONTROL DE VERSION              *
* PROGRAMAS QUE LO INVOCAN.: El programa principal                       *
* PROGRAMAS QUE INVOCA.....: Ninguno                                     *
**************************************************************************

AUTOR: Nelson Fern ndez G¢mez       FECHA DE CREACION: ENE 27/2000 JUE A
       Colombia, Bucaramanga        INICIO: 10:20 AM   ENE 27/2000 JUE

OBJETIVOS:

1- Identifica el n£mero de la versi¢n del Sistema.

2- Para cada versi¢n se detalla que cambios se realizaron


*------------------------------------------------------------------------*
*                       DETALLES DE LAS VERSIONES                        *
*------------------------------------------------------------------------*/

*>>>>VERSION ACTUAL
       LOCAL cVerSis := ' XML216.03'            // Versi¢n Actual
*>>>>FIN VERSION ACTUAL

/*
***************************************************************************
*--------------------------VERSION VY2K.01 -------------------------------*
*------------------------DETALLES DE LA VERSION --------------------------*
***************************************************************************

*>>>>REQUERIMIENTOS
     - Para los detalles de Instalaci¢n consultar directamente
       Ing Nelson Fern ndez. Celular No. 932775212
*>>>>FIN REQUERIMIENTOS

*>>>>CAMBIOS DE ESTRUCTURAS
     - Se cambio las estructuras para facilitar el trabajo con 5 periodos.
*>>>>FIN CAMBIOS DE ESTRUCTURAS

*>>>>DETALLES DE LA MODIFICACION
     - Permite trabajar con cinco periodos.
*>>>>FIN DETALLES DE LA MODIFICACION

*>>>>PASOS PARA LA ACTUALIZACION
     - Instalar solo el programa
     - Para versiones anteriores genera error si se accesa el 5 periodo
       para evitar, opcionalmente se debe actualizar las estructuras para
       para esta labor se debe consultar a Nelson Fern ndez.
*>>>>FIN PASOS PARA LA ACTUALIZACION

***************************************************************************
*--------------------------VERSION VY2K.02 -------------------------------*
*------------------------DETALLES DE LA VERSION --------------------------*
***************************************************************************

*>>>>REQUERIMIENTOS
     - Para los detalles de Instalaci¢n consultar directamente
       Ing Nelson Fern ndez. Celular No. 932775212
*>>>>FIN REQUERIMIENTOS

*>>>>CAMBIOS DE ESTRUCTURAS
     - Ninguno
*>>>>FIN CAMBIOS DE ESTRUCTURAS

*>>>>DETALLES DE LA MODIFICACION
     - Permite trabajar materias selectivas por nivel.
*>>>>FIN DETALLES DE LA MODIFICACION

*>>>>PASOS PARA LA ACTUALIZACION
     - Instalar solo el programa
*>>>>FIN PASOS PARA LA ACTUALIZACION

***************************************************************************
*--------------------------VERSION VY2K1.01-------------------------------*
*------------------------DETALLES DE LA VERSION --------------------------*
***************************************************************************

*>>>>REQUERIMIENTOS
     - Para los detalles de Instalaci¢n consultar directamente
       Ing Nelson Fern ndez. Celular No. 932775212
*>>>>FIN REQUERIMIENTOS

*>>>>CAMBIOS DE ESTRUCTURAS
     - Notas del Profesor
       +nNroLisEst => N£mero de lista
*>>>>FIN CAMBIOS DE ESTRUCTURAS

*>>>>DETALLES DE LA MODIFICACION
     - Se adiciono la opci¢n de imprimir la Hoja del Observador
     - Se adiciono la opci¢n de Actualizar la Informaci¢n de los Estudiantes
*>>>>FIN DETALLES DE LA MODIFICACION

*>>>>PASOS PARA LA ACTUALIZACION
     - Instalar solo el programa
*>>>>FIN PASOS PARA LA ACTUALIZACION

***************************************************************************
*--------------------------VERSION VY2K1.04-------------------------------*
*------------------------DETALLES DE LA VERSION --------------------------*
***************************************************************************

*>>>>REQUERIMIENTOS
     - Para los detalles de Instalaci¢n consultar directamente
       Ing Nelson Fern ndez. Celular No. 932775212
*>>>>FIN REQUERIMIENTOS

*>>>>CAMBIOS DE ESTRUCTURAS
     - Ninguna
*>>>>FIN CAMBIOS DE ESTRUCTURAS

*>>>>DETALLES DE LA MODIFICACION
     - Se corregio la seleci¢n de alumnas en las materias variables por nivel caso Barrancabermeja
*>>>>FIN DETALLES DE LA MODIFICACION

*>>>>PASOS PARA LA ACTUALIZACION
     - Instalar solo el programa
*>>>>FIN PASOS PARA LA ACTUALIZACION

*/